### PR TITLE
Fixed problem with progress bar and progress text positioning

### PR DESCRIPTION
**Pull request by vasilevladilie**
Problem with progress bar and progress text positioning:
1. In the extension popup dialog was a problem with the display of the progress bar and the progress text.
2. The progressbar.js code was not updating consistently the progress, so I did a fix for this issue in the js file.

### CODE REVIEW

**Comment by bytao7mao** [comment]
@vasilevladilie perfect ! Also, are you coming from a C, C++ or C# background ? I'm asking because of the style of your indentation 👍

**Comment by bytao7mao** [comment]
Thanks for your contribution !

**Comment by vasilevladilie** [comment]
@bytao7mao thanks. Yes, I'm a C++ developer, I worked on MirrorLink which is now deployed on PSA cars like Peugeot or Citroen. I used some time ago the curly if and else but when I read my code my style changed. I like the big blocks of code. However, we may use a beautifier for common style of coding.

**Comment by bytao7mao** [comment]
Good to know :) well done ! I am happy to have you in my team 💃

**Pull request merged**
